steps:
  # Get latest version
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/github-ops-builder"
    args: ["get-version", "${_REPO_OWNER}", "dev-tools-builder"]
    secretEnv: ["GITHUB_TOKEN"]
    id: "get-version"

  # Process PR info and bump version
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/github-ops-builder"
    args:
      - "bump-version"
      - "${_REPO_OWNER}"
      - "dev-tools-builder"
      - "--current-version"
      - "$$(cat current_version.txt)"
      - "--version-type"
      - "${_PR_TYPE}"
      - "--is-merge"
      - "${_IS_MERGE}"
      - "--pr-number"
      - "${_PR_NUMBER}"
    secretEnv: ["GITHUB_TOKEN"]
    id: "bump-version"
    waitFor: ["get-version"]

  # Build the docker image
  - name: us-central1-docker.pkg.dev/${PROJECT_ID}/docker/dev-tools-builder:packer
    entrypoint: "sh"
    args:
      - "-c"
      - "make build NEW_VERSION=$$(cat new_version.txt)"
    secretEnv: ["GITHUB_TOKEN"]
    id: "build"
    waitFor: ["bump-version"]

  # Run the tests for the built image
  - name: us-central1-docker.pkg.dev/${PROJECT_ID}/docker/dev-tools-builder:packer
    entrypoint: "make"
    args: ["test"]
    id: "test"
    waitFor: ["build"]

  # Deploy the docker image
  - name: us-central1-docker.pkg.dev/${PROJECT_ID}/docker/dev-tools-builder:packer
    entrypoint: "sh"
    args:
      - "-c"
      - "make deploy NEW_VERSION=$$(cat new_version.txt)"
    secretEnv: ["GITHUB_TOKEN"]
    id: "deploy"
    waitFor: ["test"]

  # Create GitHub release
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/github-ops-builder"
    args:
      - "create-release"
      - "${_REPO_OWNER}"
      - "dev-tools-builder"
      - "--current-version"
      - "$$(cat new_version.txt)"
      - "--is-prod"
      - "${_IS_MERGE}"
      - "--skip-asset"
    secretEnv: ["GITHUB_TOKEN"]
    waitFor: ["deploy"]
    id: "create-release"

  # Update parent repo submodule
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/github-ops-builder"
    args:
      - "update-submodule"
      - "${_REPO_OWNER}"
      - "dev-tools-builder"
      - "--parent-repo"
      - "${_PARENT_REPO}"
      - "--submodule-path"
      - "${_SUBMODULE_PATH}"
      - "--current-version"
      - "$$(cat new_version.txt)"
      - "--is-merge"
      - "${_IS_MERGE}"
    secretEnv: ["GITHUB_TOKEN"]
    id: "update-submodule"
    waitFor: ["create-release"]

substitutions:
  _LOCATION: us-central1
  _REPO_OWNER: ""
  _PR_TYPE: "timestamp" # Populated by the PR label if it exists
  _IS_MERGE: "false"
  _PR_NUMBER: "" # PR number for reference
  _PARENT_REPO: "portfolio" # Parent repository name
  _SUBMODULE_PATH: "assets/images/dev-tools-builder" # Path to submodule in parent repo

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: "projects/$PROJECT_ID/serviceAccounts/cloud-builder@${PROJECT_ID}.iam.gserviceaccount.com"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github_token/versions/latest
      env: "GITHUB_TOKEN"
